version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - /home/sajid/GitRepositories/MachineLearning/ML_Udemy_Course:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container
